# site settings
title: Cailyn Hansen
subtitle: Be Bold, Take Risks, Make Change
email: cailyn.e.hansen@gmail.com
description: I'm using technology to promote social justice,<br /> access to higher education, and civic advocacy
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Cailyn Hansen
street_address: 69 Brown St. Box 5160
city: Providence
state: RI
zip_code: 02912
country: United States of America
phone: (218) 390-2919

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 50

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cailyncodes
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/cailynhansen
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
